### ISSUE TITLE
 USSD Request throwing Exception 

### ISSUE THREAD

**Issue by halini22** [romellfudi/VoIpUSSD#73]
followed readme procedure, to make a USSD request even after giving accessibility and Phone permissions 
exceptions is being thrown:

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxx flg=0x10000000 cmp=com.android.server.telecom/.components.UserCallActivity (has extras) } from ProcessRecord{7f583ae 31356:com.example.ussd/u0a46} (pid=31356, uid=10046) with revoked permission android.permission.CALL_PHONE
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3973)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
        at android.app.Activity.startActivityForResult(Activity.java:5258)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:5216)

**Comment by romellfudi** [comment]
Write your whole exception, That previous exception is your devices should have been enabled permissions.

**Comment by halini22** [comment]
<uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACTION_MANAGE_OVERLAY_PERMISSION" />

    <uses-permission
        android:name="android.Manifest.permission.CALL_PHONE"/>
    <uses-permission android:name="android.Manifest.permission.READ_PHONE_STATE" />


 int permissionCheck = ContextCompat.checkSelfPermission(context, Manifest.permission.READ_PHONE_STATE);

                if (permissionCheck != PackageManager.PERMISSION_GRANTED) {
                    ActivityCompat.requestPermissions(MainActivity.this, new String[]{Manifest.permission.READ_PHONE_STATE}, 10);
                } else {
                         USSDApi ussdApi = USSDController.getInstance(this);
        ussdApi.callUSSDInvoke("*99#",map, new USSDController.CallbackInvoke() {
            @Override
            public void responseInvoke(String message) {
                // message has the response string data
                Log.e("Tag",message);

                String dataToSend = "1";// <- send "data" into USSD's input text
                ussdApi.send(dataToSend,new USSDController.CallbackMessage(){
                    @Override
                    public void responseMessage(String message) {
                        // message has the response string data from USSD
                        Log.e("Tag",message);
                    }
                });
            }

            @Override
            public void over(String message) {
                // message has the response string data from USSD or error
                // response no have input text, NOT SEND ANY DATA
                Log.e("Tag",message);

            }
        });
                }


Exception     -------------
2021-04-08 23:35:25.022 19987-19987/com.example.ussd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ussd, PID: 19987
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxx flg=0x10000000 cmp=com.android.server.telecom/.components.UserCallActivity (has extras) } from ProcessRecord{a4529d4 19987:com.example.ussd/u0a46} (pid=19987, uid=10046) with revoked permission android.permission.CALL_PHONE
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3973)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
        at android.app.Activity.startActivityForResult(Activity.java:5258)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:5216)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at android.app.Activity.startActivity(Activity.java:5587)
        at android.app.Activity.startActivity(Activity.java:5555)
        at com.romellfudi.ussdlibrary.USSDController.dialUp(USSDController.java:152)
        at com.romellfudi.ussdlibrary.USSDController.callUSSDInvoke(USSDController.java:111)
        at com.example.ussd.MainActivity.run(MainActivity.java:63)
        at com.example.ussd.MainActivity$1.onClick(MainActivity.java:51)
        at android.view.View.performClick(View.java:7185)
        at android.view.View.performClickInternal(View.java:7162)
        at android.view.View.access$3500(View.java:819)
        at android.view.View$PerformClick.run(View.java:27684)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by romellfudi** [comment]
Do you enable the accessibility service?

**Comment by romellfudi** [comment]
Hello @AJAYK-01 it's weird, just because that kind of error doesn't depends on api

**Comment by romellfudi** [comment]
Please @AJAYK-01 just try running my demo
